apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-dev
  namespace: argocd
spec:
  description: Project para ambiente de desenvolvimento
  sourceRepos:
    - https://github.com/org/repo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: app-dev
