apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-vendas-prd
  namespace: argocd
spec:
  description: Project do dominio vendas no prd
  sourceRepos:
    - https://github.com/org/vendas-repo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: vendas-prd
